# Based off https://github.com/MinecraftForge/SharedActions/blob/main/.github/workflows/gradle.yml
name: Gradle Pre-release CI

on:
  workflow_call:
    inputs:
      java:
        description: "The version of Java to use to run Gradle"
        required: false
        type: string
        default: "21"
      gradle_tasks:
        description: "The Gradle task(s) to run for building"
        required: false
        type: string
        default: "publish"
    secrets:
      GRADLE_ENCRYPTION_KEY:
        description: The AES key to enable Gradle cache encryption
        required: true
      CROWDIN_API_KEY:
        required: true

permissions:
  contents: read
  statuses: write
  packages: write

jobs:
  compute-version:
    uses: ./.github/workflows/gradle.version.yaml
    with:
      suffix: -rc

  gradle:
    needs: [ "compute-version" ]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: "📦 Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - id: setupJava
        name: "🔧 Setup Java"
        run: |
          echo "JAVA_HOME=$(echo $JAVA_HOME_${{ inputs.java }}_X64)" >> "$GITHUB_ENV"

      - id: setupGradle
        name: "🔧 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - id: build
        name: "🏗️ Build"
        run: ./gradlew --build-cache ${{ inputs.gradle_tasks }} -PmodVersion=${{ needs.compute-version.outputs.mod_version }} -PmodVersionSuffix=${{ needs.compute-version.outputs.suffix }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_USERNAME: ${{ github.actor }}
          crowdinKey: ${{ secrets.CROWDIN_API_KEY }}
